subscription_id    = "d4a8da62-d65b-4a7a-9ae4-800fb5384ce1"
project            = "ecommerce"
function           = "datacache"
environment        = "dev"
location           = "Central US"
admin_sql_password = "BtVfQ4GE9yLXodN"
